appname = hkzf
httpport = 8080
httpaddr = "0.0.0.0"
runmode = dev

user_id = User1
channel_id = mychannel
sdk_config = conf/local-sdk.yaml

chaincode_id_auth = authentication
chaincode_id_house = certification
chaincode_id_contract = contract
