appname = hkzf
httpport = 8080
httpaddr="0.0.0.0"
runmode = dev


user_id = User1
#chaincode config(gaj)
chaincode_id_auth = authentication
channel_id_gaj = mychannel
CORE_OGAJ_CONFIG_FILE = conf/local-sdk.yaml


#chaincode config(fgj)
chaincode_id_house = certification
channel_id_fgj = mychannel
CORE_OFGJ_CONFIG_FILE = conf/local-sdk.yaml


channel_id_union=mychannel
chaincode_id_contract=contract
CORE_CONT_CONFIG_FILE=conf/local-sdk.yaml