appname = hkzf
httpport = 8080
httpaddr = "0.0.0.0"
runmode = dev

user_id = User1
channel_id = mychannel

fabric_msp_id = Org1MSP
fabric_peer_endpoint = dns:///host.minikube.internal:7051
fabric_gateway_peer = peer0.org1.example.com
fabric_tls_cert = /app/fabric/peer-tls/ca.crt
fabric_cert_dir = /app/fabric/msp/signcerts
fabric_key_dir = /app/fabric/msp/keystore

chaincode_id_auth = authentication
chaincode_id_house = certification
chaincode_id_contract = contract
