apiVersion: apps/v1
kind: Deployment
metadata:
  name: hkzf-api
  namespace: hkzf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hkzf-api
  template:
    metadata:
      labels:
        app: hkzf-api
    spec:
      hostAliases:
        - ip: "172.17.0.1"
          hostnames:
            - "host.minikube.internal"
      containers:
        - name: hkzf-api
          image: hkzf-api:v6
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: fabric-orgs
              mountPath: /fabric/organizations
              readOnly: true
            - name: fabric-msp
              mountPath: /app/fabric/msp
            - name: peer-tls
              mountPath: /app/fabric/peer-tls
            - name: orderer-tls
              mountPath: /app/fabric/orderer-tls
      volumes:
        - name: fabric-orgs
          hostPath:
            path: FABRIC_ORGS_HOST_PATH
            type: Directory
        - name: fabric-msp
          hostPath:
            path: FABRIC_MSP_HOST_PATH
            type: Directory
        - name: peer-tls
          hostPath:
            path: FABRIC_PEER_TLS_HOST_PATH
            type: Directory
        - name: orderer-tls
          hostPath:
            path: FABRIC_ORDERER_TLS_HOST_PATH
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: hkzf-api
  namespace: hkzf
spec:
  type: NodePort
  selector:
    app: hkzf-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
